name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v0
    secrets: inherit

  test-against-coordinator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the canonical/tempo-worker-k8s-operator repository (this branch)
        uses: actions/checkout@v4
        with:
          path: "worker"
          # leave other args blank: it's checking out THIS branch/THIS repo

      - name: Checkout the canonical/tempo-coordinator-k8s-operator repository
        uses: actions/checkout@v4
        with:
          repository: canonical/tempo-coordinator-k8s-operator
          path: "coordinator"
          ref: main

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install tox~=4.2

      - name: Setup Charmcraft's pip cache
        uses: actions/cache@v4
        with:
          path: /home/runner/snap/charmcraft/common/cache/charmcraft/
          key: charmcraft-cache-${{ github.job }}-${{ strategy.job-index }}-${{ github.run_id }}-${{ github.run_attempt }}
          restore-keys: charmcraft-cache

      - name: Get IP range
        id: ip_range
        run: |
          echo "ip_range=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')/32" >> $GITHUB_OUTPUT

      - name: Setup operator environment (k8s)
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.4/stable
          provider: microk8s
          channel: 1.26-strict/stable
          microk8s-group: snap_microk8s
          microk8s-addons: "hostpath-storage dns metallb:${{ steps.ip_range.outputs.ip_range }} rbac"
          charmcraft-channel: "3.x/candidate"

      - name: Build the worker charm
        run: charmcraft pack -p ./worker

      - name: Run the coordinator charm's integration tests
        run: cd coordinator; TEMPO_WORKER_CHARM=$GITHUB_WORKSPACE/tempo-worker-k8s_ubuntu-22.04-amd64.charm tox -vve integration

  
  terraform-checks:
    name: Terraform
    uses: canonical/observability/.github/workflows/terraform-quality-checks.yaml@v0
